### ISSUE TITLE
Template roto(bug)

### ISSUE THREAD

**Issue by MarceloGallardoMadrid** [benjumea12/la-filmo#8]
DSR!
les quedo un tag en uno de los templates rotos, igual no rompe nada mepa
```code
<img src="https://generacionmaldita.com/wp-content/uploads/2023/04/14-El-lenguaje-es-M4T3MAT1C0-Ugly-doll-768x432.png; ?>" alt="Ilustración del corto 'El lenguaje es matemático'">
```

**Comment by MarceloGallardoMadrid** [comment]
No se a que hace referencia porque el link anda

**Comment by xchwarze** [comment]
@MarceloGallardoMadrid a que al estar mal el src queda mal porque tiene el tag de cerrar el php concatenado
Por eso puse que anda igual, pero no deja de ser un error

**Comment by xchwarze** [comment]
es un dedaso que se les paso en https://github.com/benjumea12/la-filmo/commit/7f15bf682aeef3f8f2bb8fe0188cd38c860f1b98
ahi les mando pr
